# Generated by Django 3.0 on 2020-04-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200414_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='description_projet',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description du capteur '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='interested_profile', to='classroom.Subject'),
        ),
    ]
